# codecov removed 2021-04-15 after security breach notice

stages:
  - build
  - push
  
  
variables:
  DOCKER_IMAGE:             "${CI_REGISTRY_IMAGE}/docker:19"
  DOCKER_DIND_IMAGE:        "${CI_REGISTRY_IMAGE}/gitlab-ci-dind:latest"


Build:
  stage: build
  tags:
    - openstack-autoscale-theta
  script:
    - docker info
    - echo "🐳 Building ${IMAGE_NAME}:${CI_COMMIT_TAG} 🐳"
    - docker pull ${IMAGE_NAME}:latest || true
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${IMAGE_NAME}:latest --tag ${IMAGE_NAME}:${CI_COMMIT_TAG} ./api/
    - echo "🐳 Pushing ${IMAGE_NAME}:${CI_COMMIT_TAG} 🐳"
    - docker push ${IMAGE_NAME}:${CI_COMMIT_TAG}

# at every release/tag, tag the images built from the latest image builds as 'latest'
Push tag:
  variables:
    # only working with docker images; don't need to clone repo
    GIT_STRATEGY: none
  stage: push
  tags:
    - openstack-autoscale-theta
  only:
    - tags
  script:
    - docker pull ${IMAGE_NAME}:${CI_COMMIT_TAG}
    - >
         for this_tag in $CI_COMMIT_REF_NAME 'latest'; do
            docker tag  ${IMAGE_NAME}:${CI_COMMIT_TAG} ${IMAGE_NAME}:${this_tag}
            echo "🐳 Pushing ${IMAGE_NAME}:${this_tag} 🐳"
            docker push ${IMAGE_NAME}:${this_tag}
         done